<!--BOOK_INFORMATION-->
<img align="left" style="padding-right:10px;" src="figures/PDSH-cover-small.png">
*This notebook contains an excerpt from the book Machine Learning for OpenCV by Michael Beyeler; the content is available [on GitHub](https://github.com/mbeyeler/opencv-machine-learning).*

*The text is released under the [CC-BY-NC-ND license](https://creativecommons.org/licenses/by-nc-nd/3.0/us/legalcode), and code is released under the [MIT license](https://opensource.org/licenses/MIT). If you find this content useful, please consider supporting the work by [buying the book](https://github.com/mbeyeler/opencv-machine-learning)!*

<!--NAVIGATION-->
< [Dealing with Data Using OpenCV's TrainData Container in C++](02.05-Dealing-with-Data-Using-the-OpenCV-TrainData-Container-in-C++.ipynb) | [Contents](../README.md) | [None](04.00-Representing-Data-and-Engineering-Features.ipynb) >

## Scoring classifiers using accuracy, precision, and recall

In [1]:
import numpy as np

In [2]:
np.random.seed(42)

In [3]:
y_true = np.random.randint(0, 2, size=5)
y_true

array([0, 1, 0, 0, 0])

In [4]:
y_pred = np.ones(5, dtype=np.int32)
y_pred

array([1, 1, 1, 1, 1])

In [5]:
np.sum(y_true == y_pred) / len(y_true)

0.20000000000000001

In [6]:
from sklearn import metrics

In [7]:
metrics.accuracy_score(y_true, y_pred)

0.20000000000000001

In [8]:
truly_a_positive = (y_true == 1)

In [9]:
predicted_a_positive = (y_pred == 1)

In [10]:
# You thought it was a 1, and it actually was a 1
true_positive = np.sum(predicted_a_positive * truly_a_positive)
true_positive

1

In [11]:
# You thought it was a 1, but it was actually a 0
false_positive = np.sum((y_pred == 1) * (y_true == 0))
false_positive

4

In [12]:
# You thought it was a 0, but it actually was a 1
false_negative = np.sum((y_pred == 0) * (y_true == 1))
false_negative

0

In [13]:
# You thought it was a 0, and it actually was a 0
true_negative = (y_pred == 0) * (y_true == 0)
true_negative

array([False, False, False, False, False], dtype=bool)

In [14]:
accuracy = np.sum(true_positive + true_negative) / len(y_true)
accuracy

1.0

In [15]:
precision = np.sum(true_positive) / np.sum(true_positive + true_negative)
precision

0.20000000000000001

In [16]:
metrics.precision_score(y_true, y_pred)

0.20000000000000001

In [17]:
recall = true_positive / (true_positive + false_negative)
recall

1.0

In [18]:
metrics.recall_score(y_true, y_pred)

1.0

## Scoring regressors using mean squared error, explained variance, and the coefficient of determination

<!--NAVIGATION-->
< [Dealing with Data Using OpenCV's TrainData Container in C++](02.05-Dealing-with-Data-Using-the-OpenCV-TrainData-Container-in-C++.ipynb) | [Contents](../README.md) | [None](04.00-Representing-Data-and-Engineering-Features.ipynb) >